### ISSUE TITLE
咨询关于词表的构建

### ISSUE THREAD

**Issue by xzdong-2019** [guotong1988/chinese_dictionary#1]
hello，  您好，
       想问一下，词表的构建依据依据来源是啥？是新华字典库吗？还是靠一些其他技术挖掘的啊？我现在考虑构建行业内的某些同义字典，人工构造的方法太慢了，有没有什么好的方法的推荐啊？非常感谢您的回答。

**Comment by guotong1988** [comment]
我也不太清楚

**Comment by guotong1988** [comment]
这个就是网上找的
