### ISSUE TITLE
Have you got any guides how to use the data?

### ISSUE THREAD

**Issue by catusf** [guotong1988/chinese_dictionary#3]
Hi @guotong1988 
Among 3 files, dict_negative.txt and dict_antonym.txt are quite obvious.

But dict_synonym.txt is a bit confusing. Any guides how to use this?

Many thanks for your work.

**Comment by guotong1988** [comment]
Sorry, I do not have guides.

**Comment by catusf** [comment]
@guotong1988 can you tell me where did you take the data from?

**Comment by guotong1988** [comment]
I forgot.

**Comment by catusf** [comment]
Thanks anyway.
